{% set name = "dart-sdk" %}
{% set version = "2.17.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-macos-x64-release.zip"    # [osx and x86_64]
    sha256: "9b1881c4167bba76c6ac0f92bbdb777a9d2b89c62977a7e95c37e028ecb9fa62"                                                    # [osx and x86_64]
  - url: "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-macos-arm64-release.zip"  # [osx and arm64]
    sha256: "9c655ab17e1239dcd3ba56d8a9483ee298dc92eea305a46a10b2fccfc7e441f2"                                                    # [osx and arm64]
  - url: "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-x64-release.zip"    # [linux and x86_64]
    sha256: "f837f385603a1cfb14ddb7dd0cd64820b297646626bdb689ccfc3278fa83b2b1"                                                    # [linux and x86_64]
  - url: "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-arm64-release.zip"  # [linux and aarch64]
    sha256: "8e71b0c958a587c83ecd6c8cc637bc624bb85bc64e877e9ea00831a659a904b1"                                                    # [linux and aarch64]
  - url: "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-windows-x64-release.zip"  # [win]
    sha256: "a0671592e21d662ea3c815dddb6f7a0a963fcdaf9a2528c844bb9185605ca95c"                                                    # [win]

build:
  number: 0
  binary_relocation: False
  missing_dso_whitelist:
    # normal linux stuff that would go away if we had libgcc-ng in the run deps
    - "*/ld-linux.so.2"
    - "*/lib64/ld-linux-x86-64.so.2"
    - "*/libpthread.so.0"
    - "*/libdl.so.2"
    - "*/libm.so.6"
    - "*/libc.so.6"

outputs:
  # define a mutex because the aot package calls the `dartaotruntime` simply `dart` and we don't want to confuse that with the SDK's fatter `dart` executable
  - name: _dart-runtime-mutex
    version: 1.0
    build:
      string: {{ dart_runtime_selector }}
    test:
      commands:
        - echo "Dummy test to appease linter"

  - name: dart-aot-runtime
    script: copy_aot_runtime.sh   # [unix]
    script: copy_aot_runtime.bat  # [win]
    requirements:
      - _dart-runtime-mutex 1.0-aot
    test:
      commands:
        - dart --help
    about:
      home: https://dart.dev/
      license: BSD-3-Clause
      license_file:
        - LICENSE
      summary: a client-optimized language for developing fast apps on any platform (AoT runtime only)

  - name: dart-sdk
    script: copy_sdk.sh   # [unix]
    script: copy_sdk.bat  # [win]
    requirements:
      - _dart-runtime-mutex 1.0-sdk
    test:
      commands:
        - dart --help

about:
  home: https://dart.dev/
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: a client-optimized language for developing fast apps on any platform

extra:
  recipe-maintainers:
    - msarahan
